In [37]:
# Import PyTorch to check whether Kaggle provides a GPU
import torch

# Check if CUDA/GPU is available
print("CUDA available:", torch.cuda.is_available())

# Print the GPU name if CUDA is available
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

CUDA available: True
GPU: Tesla T4

In [38]:
# Import os for working with Kaggle folders and files
import os

# Define the main Kaggle input directory

INPUT_DIR = "/kaggle/input"

# Search through Kaggle's input directory
for root, dirs, files in os.walk(INPUT_DIR):

    # Check whether train.csv exists in the current folder
    if "train.csv" in files:

        # Save the folder containing train.csv
        DATA_DIR = root

        # Stop searching after finding the dataset
        break

# Define the training audio folder
TRAIN_DIR = os.path.join(DATA_DIR, "train")

# Define the testing audio folder
TEST_DIR = os.path.join(DATA_DIR, "test")

# Define the training CSV path
TRAIN_CSV = os.path.join(DATA_DIR, "train.csv")

# Define the testing CSV path
TEST_CSV = os.path.join(DATA_DIR, "test.csv")

# Define the sample submission path
SAMPLE_SUBMISSION = os.path.join(DATA_DIR, "sample_submission.csv")

# Print all important paths
print("DATA_DIR:", DATA_DIR)
print("TRAIN_DIR:", TRAIN_DIR)
print("TEST_DIR:", TEST_DIR)
print("TRAIN_CSV:", TRAIN_CSV)
print("TEST_CSV:", TEST_CSV)
print("SAMPLE_SUBMISSION:", SAMPLE_SUBMISSION)

DATA_DIR: /kaggle/input/competitions/shl-hiring-assessment-2026/Dataset_Final
TRAIN_DIR: /kaggle/input/competitions/shl-hiring-assessment-2026/Dataset_Final/train
TEST_DIR: /kaggle/input/competitions/shl-hiring-assessment-2026/Dataset_Final/test
TRAIN_CSV: /kaggle/input/competitions/shl-hiring-assessment-2026/Dataset_Final/train.csv
TEST_CSV: /kaggle/input/competitions/shl-hiring-assessment-2026/Dataset_Final/test.csv
SAMPLE_SUBMISSION: /kaggle/input/competitions/shl-hiring-assessment-2026/Dataset_Final/sample_submission.csv

In [39]:
# Import pandas for reading the CSV files
import pandas as pd

# Load the training metadata
train_df = pd.read_csv(TRAIN_CSV)

# Load the testing metadata
test_df = pd.read_csv(TEST_CSV)

# Display the training shape
print("Training shape:", train_df.shape)

# Display the testing shape
print("Testing shape:", test_df.shape)

# Display the training columns
print("Training columns:", train_df.columns.tolist())

# Display the first five training rows
display(train_df.head())

# Display the first five testing rows
display(test_df.head())

Training shape: (769, 2)
Testing shape: (216, 2)
Training columns: ['filename', 'label']

        filename  label
0  audio_192.wav    3.0
1  audio_436.wav    3.0
2  audio_447.wav    3.5
3  audio_126.wav    2.0
4   audio_61.wav    2.0

        filename  label
0  audio_128.wav     -1
1  audio_156.wav     -1
2   audio_19.wav     -1
3  audio_108.wav     -1
4  audio_206.wav     -1

In [41]:
# Import pandas for reading CSV files
import pandas as pd

# Load the training metadata
train_df = pd.read_csv(TRAIN_CSV)

# Load the testing metadata
test_df = pd.read_csv(TEST_CSV)

# Print the number of training rows and columns
print("Training shape:", train_df.shape)

# Print the number of testing rows and columns
print("Testing shape:", test_df.shape)

# Print the training column names
print("Training columns:", train_df.columns.tolist())

# Print the testing column names
print("Testing columns:", test_df.columns.tolist())

# Display the first five training records
display(train_df.head())

# Display the first five testing records
display(test_df.head())

Training shape: (769, 2)
Testing shape: (216, 2)
Training columns: ['filename', 'label']
Testing columns: ['filename', 'label']

        filename  label
0  audio_192.wav    3.0
1  audio_436.wav    3.0
2  audio_447.wav    3.5
3  audio_126.wav    2.0
4   audio_61.wav    2.0

        filename  label
0  audio_128.wav     -1
1  audio_156.wav     -1
2   audio_19.wav     -1
3  audio_108.wav     -1
4  audio_206.wav     -1

In [42]:
# Upgrade/install the main libraries needed for the advanced speech model
%pip install -q transformers accelerate librosa soundfile tqdm xgboost lightgbm catboost

Note: you may need to restart the kernel to use updated packages.

In [44]:
# Import operating-system utilities
import os

# Import NumPy for numerical arrays
import numpy as np

# Import pandas for tabular data
import pandas as pd

# Import PyTorch for GPU-accelerated deep learning
import torch

# Import librosa for loading and processing audio
import librosa

# Import tqdm for progress bars
from tqdm.auto import tqdm

# Import the Wav2Vec2 processor
from transformers import Wav2Vec2Processor

# Import the Wav2Vec2 model
from transformers import Wav2Vec2Model


# Check whether CUDA/GPU is available
print("CUDA available:", torch.cuda.is_available())

# Select the Tesla T4 if CUDA is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Print the device being used
print("Using device:", device)

# Print the GPU name
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

CUDA available: True
Using device: cuda
GPU: Tesla T4

In [45]:
# Define the pretrained Wav2Vec2-large speech model
MODEL_NAME = "facebook/wav2vec2-large-960h"

# Load the audio processor associated with the model
processor = Wav2Vec2Processor.from_pretrained(MODEL_NAME)

# Load the pretrained Wav2Vec2-large model
wav2vec_model = Wav2Vec2Model.from_pretrained(
    MODEL_NAME
)

# Move the model from CPU to the Tesla T4 GPU
wav2vec_model = wav2vec_model.to(device)

# Put the model into evaluation mode
wav2vec_model.eval()

# Print confirmation
print("Wav2Vec2-large loaded successfully.")

# Print the hidden representation size
print("Hidden size:", wav2vec_model.config.hidden_size)

preprocessor_config.json:   0%|          | 0.00/159 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/843 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 1.26GB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/402 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.26GB

model.safetensors: downloading bytes:           |  0.00B

[transformers] Wav2Vec2Model LOAD REPORT from: facebook/wav2vec2-large-960h
Key               | Status     |
------------------+------------+-
lm_head.weight    | UNEXPECTED |
lm_head.bias      | UNEXPECTED |
masked_spec_embed | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Wav2Vec2-large loaded successfully.
Hidden size: 1024

In [46]:
# Import NumPy for numerical operations
import numpy as np

# Import librosa for loading WAV audio
import librosa

# Select the first training audio filename
sample_filename = train_df.iloc[0]["filename"]

# Build the complete path to that audio file
sample_path = os.path.join(TRAIN_DIR, sample_filename)

# Load the audio at 16 kHz and convert it to mono
audio, sample_rate = librosa.load(
    sample_path,
    sr=16000,
    mono=True
)

# Print the audio information
print("Filename:", sample_filename)
print("Sample rate:", sample_rate)
print("Duration:", round(len(audio) / sample_rate, 2), "seconds")

# Convert the NumPy audio array into the format expected by Wav2Vec2
inputs = processor(
    audio,
    sampling_rate=16000,
    return_tensors="pt"
)

# Move the input tensor to the Tesla T4 GPU
input_values = inputs.input_values.to(device)

# Disable gradient calculation because we only need embeddings
with torch.no_grad():

    # Run the audio through Wav2Vec2-large
    outputs = wav2vec_model(
        input_values,
        output_hidden_states=True
    )

# Take the final hidden representation
last_hidden = outputs.last_hidden_state

# Mean-pool across the time dimension
sample_embedding = last_hidden.mean(dim=1).squeeze(0)

# Move the embedding back to CPU and convert it to NumPy
sample_embedding = sample_embedding.cpu().numpy()

# Print the resulting embedding shape
print("Embedding shape:", sample_embedding.shape)

Filename: audio_192.wav
Sample rate: 16000
Duration: 60.51 seconds
Embedding shape: (1024,)

In [47]:
# Import os for file and folder operations
import os

# Import NumPy for storing embeddings
import numpy as np

# Import librosa for loading audio
import librosa

# Import tqdm for a progress bar
from tqdm.auto import tqdm

# Define where the training embeddings will be saved
TRAIN_EMBED_PATH = "/kaggle/working/train_wav2vec.npy"

# Create a list to store all training embeddings
train_embeddings = []

# Create a list to keep the filenames in the exact training order
train_embedding_names = []

# Process every training audio file
for filename in tqdm(
    train_df["filename"].tolist(),
    desc="Extracting train Wav2Vec2 embeddings"
):

    # Build the complete audio path
    audio_path = os.path.join(TRAIN_DIR, filename)

    # Load the audio at 16 kHz
    audio, sr = librosa.load(
        audio_path,
        sr=16000,
        mono=True
    )

    # Convert the audio into Wav2Vec2 input tensors
    inputs = processor(
        audio,
        sampling_rate=16000,
        return_tensors="pt"
    )

    # Move the input to the Tesla T4 GPU
    input_values = inputs.input_values.to(device)

    # Disable gradients because this is feature extraction
    with torch.no_grad():

        # Run the audio through Wav2Vec2-large
        outputs = wav2vec_model(
            input_values
        )

    # Get the final hidden representation
    hidden = outputs.last_hidden_state

    # Mean-pool across the time dimension
    embedding = hidden.mean(
        dim=1
    ).squeeze(0)

    # Move embedding to CPU and convert it to NumPy
    embedding = embedding.cpu().numpy()

    # Store the embedding
    train_embeddings.append(embedding)

    # Store the corresponding filename
    train_embedding_names.append(filename)

# Convert the list into a NumPy matrix
train_embeddings = np.vstack(train_embeddings)

# Save the embeddings to Kaggle working storage
np.save(
    TRAIN_EMBED_PATH,
    train_embeddings
)

# Print the final matrix shape
print("Training embeddings shape:", train_embeddings.shape)

# Print the saved file location
print("Saved to:", TRAIN_EMBED_PATH)

Extracting train Wav2Vec2 embeddings:   0%|          | 0/769 [00:00<?, ?it/s]

Training embeddings shape: (769, 1024)
Saved to: /kaggle/working/train_wav2vec.npy

In [48]:
# Define where the test embeddings will be saved
TEST_EMBED_PATH = "/kaggle/working/test_wav2vec.npy"

# Create a list to store all test embeddings
test_embeddings = []

# Process every test audio file
for filename in tqdm(
    test_df["filename"].tolist(),
    desc="Extracting test Wav2Vec2 embeddings"
):

    # Build the complete path to the test audio file
    audio_path = os.path.join(TEST_DIR, filename)

    # Load the audio at 16 kHz
    audio, sr = librosa.load(
        audio_path,
        sr=16000,
        mono=True
    )

    # Convert audio into Wav2Vec2 input tensors
    inputs = processor(
        audio,
        sampling_rate=16000,
        return_tensors="pt"
    )

    # Move the input to the Tesla T4 GPU
    input_values = inputs.input_values.to(device)

    # Disable gradients because we only need embeddings
    with torch.no_grad():

        # Run the audio through Wav2Vec2-large
        outputs = wav2vec_model(
            input_values
        )

    # Get the final hidden representation
    hidden = outputs.last_hidden_state

    # Mean-pool across the time dimension
    embedding = hidden.mean(
        dim=1
    ).squeeze(0)

    # Move embedding to CPU and convert it to NumPy
    embedding = embedding.cpu().numpy()

    # Store the embedding
    test_embeddings.append(embedding)

# Convert the list into a NumPy matrix
test_embeddings = np.vstack(test_embeddings)

# Save the test embeddings
np.save(
    TEST_EMBED_PATH,
    test_embeddings
)

# Print the final matrix shape
print("Test embeddings shape:", test_embeddings.shape)

# Print the saved file location
print("Saved to:", TEST_EMBED_PATH)

Extracting test Wav2Vec2 embeddings:   0%|          | 0/216 [00:00<?, ?it/s]

Test embeddings shape: (216, 1024)
Saved to: /kaggle/working/test_wav2vec.npy

In [49]:
# Import librosa for audio and speech features
import librosa

# Import NumPy for numerical calculations
import numpy as np

# Import pandas for creating feature tables
import pandas as pd

# Import os for file paths
import os

# Import tqdm for a progress bar
from tqdm.auto import tqdm


# Define a function to extract acoustic and prosodic features
def extract_acoustic_features(audio_path):

    # Load the audio at 16 kHz
    y, sr = librosa.load(
        audio_path,
        sr=16000,
        mono=True
    )

    # Protect against empty audio files
    if len(y) == 0:
        return np.zeros(25, dtype=np.float32)

    # Calculate audio duration in seconds
    duration = len(y) / sr

    # Calculate RMS energy
    rms = librosa.feature.rms(y=y)[0]

    # Calculate zero-crossing rate
    zcr = librosa.feature.zero_crossing_rate(y)[0]

    # Calculate spectral centroid
    centroid = librosa.feature.spectral_centroid(
        y=y,
        sr=sr
    )[0]

    # Calculate spectral bandwidth
    bandwidth = librosa.feature.spectral_bandwidth(
        y=y,
        sr=sr
    )[0]

    # Calculate spectral rolloff
    rolloff = librosa.feature.spectral_rolloff(
        y=y,
        sr=sr
    )[0]

    # Calculate pitch using librosa's YIN algorithm
    f0 = librosa.yin(
        y,
        fmin=70,
        fmax=400,
        sr=sr
    )

    # Keep only valid pitch values
    valid_f0 = f0[np.isfinite(f0)]

    # Calculate onset strength
    onset = librosa.onset.onset_strength(
        y=y,
        sr=sr
    )

    # Calculate short-time energy changes
    energy_change = np.diff(rms)

    # Calculate approximate silence proportion
    silence_ratio = np.mean(rms < (np.max(rms) * 0.05))

    # Calculate speech activity ratio
    speech_ratio = 1.0 - silence_ratio

    # Calculate estimated speaking activity from onset rate
    onset_rate = len(
        librosa.onset.onset_detect(
            y=y,
            sr=sr
        )
    ) / max(duration, 1e-6)

    # Calculate pitch statistics
    if len(valid_f0) > 0:

        # Mean pitch
        pitch_mean = np.mean(valid_f0)

        # Standard deviation of pitch
        pitch_std = np.std(valid_f0)

        # Minimum pitch
        pitch_min = np.min(valid_f0)

        # Maximum pitch
        pitch_max = np.max(valid_f0)

    else:

        # Use zeros if pitch could not be detected
        pitch_mean = 0.0
        pitch_std = 0.0
        pitch_min = 0.0
        pitch_max = 0.0

    # Build the acoustic feature vector
    features = [

        # Duration
        duration,

        # RMS statistics
        np.mean(rms),
        np.std(rms),
        np.min(rms),
        np.max(rms),

        # ZCR statistics
        np.mean(zcr),
        np.std(zcr),

        # Spectral centroid statistics
        np.mean(centroid),
        np.std(centroid),

        # Spectral bandwidth statistics
        np.mean(bandwidth),
        np.std(bandwidth),

        # Spectral rolloff statistics
        np.mean(rolloff),
        np.std(rolloff),

        # Pitch statistics
        pitch_mean,
        pitch_std,
        pitch_min,
        pitch_max,

        # Onset statistics
        np.mean(onset),
        np.std(onset),

        # Energy change statistics
        np.mean(energy_change) if len(energy_change) else 0.0,
        np.std(energy_change) if len(energy_change) else 0.0,

        # Silence/speech statistics
        silence_ratio,
        speech_ratio,

        # Estimated onset rate
        onset_rate,

        # Number of detected pitch frames
        len(valid_f0)
    ]

    # Return the feature vector as float32
    return np.asarray(
        features,
        dtype=np.float32
    )


# Create a list for training acoustic features
train_acoustic = []

# Extract features from every training audio file
for filename in tqdm(
    train_df["filename"].tolist(),
    desc="Extracting train acoustic features"
):

    # Build the audio path
    audio_path = os.path.join(
        TRAIN_DIR,
        filename
    )

    # Extract acoustic features
    features = extract_acoustic_features(
        audio_path
    )

    # Store the features
    train_acoustic.append(features)


# Create a list for test acoustic features
test_acoustic = []

# Extract features from every test audio file
for filename in tqdm(
    test_df["filename"].tolist(),
    desc="Extracting test acoustic features"
):

    # Build the audio path
    audio_path = os.path.join(
        TEST_DIR,
        filename
    )

    # Extract acoustic features
    features = extract_acoustic_features(
        audio_path
    )

    # Store the features
    test_acoustic.append(features)


# Convert training features into a NumPy matrix
train_acoustic = np.vstack(train_acoustic)

# Convert test features into a NumPy matrix
test_acoustic = np.vstack(test_acoustic)


# Print the training feature shape
print("Train acoustic shape:", train_acoustic.shape)

# Print the test feature shape
print("Test acoustic shape:", test_acoustic.shape)

Extracting train acoustic features:   0%|          | 0/769 [00:00<?, ?it/s]

Extracting test acoustic features:   0%|          | 0/216 [00:00<?, ?it/s]

Train acoustic shape: (769, 25)
Test acoustic shape: (216, 25)

In [50]:
# Combine Wav2Vec2 embeddings with acoustic features for training
X_train_raw = np.hstack([
    train_embeddings,
    train_acoustic
])

# Combine Wav2Vec2 embeddings with acoustic features for testing
X_test_raw = np.hstack([
    test_embeddings,
    test_acoustic
])

# Extract the target grammar scores
y = train_df["label"].values.astype(np.float32)

# Print the combined training shape
print("Combined train shape:", X_train_raw.shape)

# Print the combined test shape
print("Combined test shape:", X_test_raw.shape)

# Print the target shape
print("Target shape:", y.shape)

# Check for missing values in the training features
print(
    "Training NaN count:",
    np.isnan(X_train_raw).sum()
)

# Check for missing values in the test features
print(
    "Test NaN count:",
    np.isnan(X_test_raw).sum()
)

Combined train shape: (769, 1049)
Combined test shape: (216, 1049)
Target shape: (769,)
Training NaN count: 0
Test NaN count: 0

In [51]:
# Import StandardScaler for feature normalization
from sklearn.preprocessing import StandardScaler

# Import PCA for dimensionality reduction
from sklearn.decomposition import PCA


# Separate the Wav2Vec2 features from acoustic features
X_train_w2v = X_train_raw[:, :1024]

# Separate the test Wav2Vec2 features
X_test_w2v = X_test_raw[:, :1024]

# Separate the acoustic features
X_train_acoustic = X_train_raw[:, 1024:]

# Separate the test acoustic features
X_test_acoustic = X_test_raw[:, 1024:]


# Create a scaler for Wav2Vec2 features
w2v_scaler = StandardScaler()

# Fit the scaler only on training Wav2Vec2 features
X_train_w2v_scaled = w2v_scaler.fit_transform(
    X_train_w2v
)

# Transform test Wav2Vec2 features using the same scaler
X_test_w2v_scaled = w2v_scaler.transform(
    X_test_w2v
)


# Create PCA retaining 95% of the variance
w2v_pca = PCA(
    n_components=0.95,
    random_state=42
)

# Fit PCA using only training data
X_train_w2v_pca = w2v_pca.fit_transform(
    X_train_w2v_scaled
)

# Transform the test data
X_test_w2v_pca = w2v_pca.transform(
    X_test_w2v_scaled
)


# Scale the acoustic features
acoustic_scaler = StandardScaler()

# Fit acoustic scaler on training data
X_train_acoustic_scaled = acoustic_scaler.fit_transform(
    X_train_acoustic
)

# Transform test acoustic features
X_test_acoustic_scaled = acoustic_scaler.transform(
    X_test_acoustic
)


# Combine reduced Wav2Vec2 features with acoustic features
X_train = np.hstack([
    X_train_w2v_pca,
    X_train_acoustic_scaled
])

# Combine test features
X_test = np.hstack([
    X_test_w2v_pca,
    X_test_acoustic_scaled
])


# Print PCA information
print(
    "Original Wav2Vec2 dimensions:",
    X_train_w2v.shape[1]
)

print(
    "Reduced Wav2Vec2 dimensions:",
    X_train_w2v_pca.shape[1]
)

print(
    "Explained variance:",
    round(
        w2v_pca.explained_variance_ratio_.sum(),
        4
    )
)

# Print final model feature dimensions
print(
    "Final train shape:",
    X_train.shape
)

print(
    "Final test shape:",
    X_test.shape
)

Original Wav2Vec2 dimensions: 1024
Reduced Wav2Vec2 dimensions: 99
Explained variance: 0.9506
Final train shape: (769, 124)
Final test shape: (216, 124)

In [52]:
# Import KFold for cross-validation
from sklearn.model_selection import KFold

# Import regression evaluation metric
from sklearn.metrics import mean_squared_error

# Import Pearson correlation
from scipy.stats import pearsonr

# Import Ridge regression
from sklearn.linear_model import Ridge

# Import Support Vector Regression
from sklearn.svm import SVR

# Import Random Forest
from sklearn.ensemble import RandomForestRegressor

# Import XGBoost
from xgboost import XGBRegressor

# Import LightGBM
from lightgbm import LGBMRegressor

# Import CatBoost
from catboost import CatBoostRegressor

# Import NumPy
import numpy as np


# Create 10-fold cross-validation
kf = KFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# Create OOF predictions for XGBoost
oof_xgb = np.zeros(len(X_train))

# Create OOF predictions for LightGBM
oof_lgb = np.zeros(len(X_train))

# Create OOF predictions for CatBoost
oof_cat = np.zeros(len(X_train))

# Create OOF predictions for Random Forest
oof_rf = np.zeros(len(X_train))

# Create OOF predictions for Ridge
oof_ridge = np.zeros(len(X_train))

# Create OOF predictions for SVR
oof_svr = np.zeros(len(X_train))


# Create test prediction arrays
test_xgb = np.zeros(len(X_test))
test_lgb = np.zeros(len(X_test))
test_cat = np.zeros(len(X_test))
test_rf = np.zeros(len(X_test))
test_ridge = np.zeros(len(X_test))
test_svr = np.zeros(len(X_test))


# Start 10-fold cross-validation
for fold, (train_idx, valid_idx) in enumerate(
    kf.split(X_train),
    start=1
):

    # Print the current fold
    print(f"\n========== Fold {fold}/10 ==========")

    # Get training features for this fold
    X_tr = X_train[train_idx]

    # Get validation features for this fold
    X_val = X_train[valid_idx]

    # Get training targets for this fold
    y_tr = y[train_idx]

    # Get validation targets for this fold
    y_val = y[valid_idx]


    # -----------------------------
    # XGBoost
    # -----------------------------

    # Create the XGBoost model
    xgb_model = XGBRegressor(
        n_estimators=1000,
        learning_rate=0.025,
        max_depth=5,
        min_child_weight=5,
        subsample=0.85,
        colsample_bytree=0.85,
        reg_alpha=0.1,
        reg_lambda=2.0,
        objective="reg:squarederror",
        random_state=42,
        n_jobs=-1
    )

    # Train XGBoost
    xgb_model.fit(
        X_tr,
        y_tr
    )

    # Generate validation predictions
    oof_xgb[valid_idx] = xgb_model.predict(X_val)

    # Generate test predictions and average across folds
    test_xgb += xgb_model.predict(X_test) / 10


    # -----------------------------
    # LightGBM
    # -----------------------------

    # Create the LightGBM model
    lgb_model = LGBMRegressor(
        n_estimators=1000,
        learning_rate=0.025,
        max_depth=6,
        num_leaves=31,
        subsample=0.85,
        colsample_bytree=0.85,
        reg_alpha=0.1,
        reg_lambda=2.0,
        random_state=42,
        verbosity=-1,
        n_jobs=-1
    )

    # Train LightGBM
    lgb_model.fit(
        X_tr,
        y_tr
    )

    # Generate validation predictions
    oof_lgb[valid_idx] = lgb_model.predict(X_val)

    # Generate test predictions
    test_lgb += lgb_model.predict(X_test) / 10


    # -----------------------------
    # CatBoost
    # -----------------------------

    # Create the CatBoost model
    cat_model = CatBoostRegressor(
        iterations=1000,
        depth=6,
        learning_rate=0.03,
        loss_function="RMSE",
        verbose=False,
        random_seed=42
    )

    # Train CatBoost
    cat_model.fit(
        X_tr,
        y_tr
    )

    # Generate validation predictions
    oof_cat[valid_idx] = cat_model.predict(X_val)

    # Generate test predictions
    test_cat += cat_model.predict(X_test) / 10


    # -----------------------------
    # Random Forest
    # -----------------------------

    # Create the Random Forest model
    rf_model = RandomForestRegressor(
        n_estimators=500,
        max_features=0.75,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1
    )

    # Train Random Forest
    rf_model.fit(
        X_tr,
        y_tr
    )

    # Generate validation predictions
    oof_rf[valid_idx] = rf_model.predict(X_val)

    # Generate test predictions
    test_rf += rf_model.predict(X_test) / 10


    # -----------------------------
    # Ridge
    # -----------------------------

    # Create Ridge regression
    ridge_model = Ridge(
        alpha=10.0
    )

    # Train Ridge
    ridge_model.fit(
        X_tr,
        y_tr
    )

    # Generate validation predictions
    oof_ridge[valid_idx] = ridge_model.predict(X_val)

    # Generate test predictions
    test_ridge += ridge_model.predict(X_test) / 10


    # -----------------------------
    # SVR
    # -----------------------------

    # Create Support Vector Regression
    svr_model = SVR(
        C=10.0,
        epsilon=0.05,
        gamma="scale"
    )

    # Train SVR
    svr_model.fit(
        X_tr,
        y_tr
    )

    # Generate validation predictions
    oof_svr[valid_idx] = svr_model.predict(X_val)

    # Generate test predictions
    test_svr += svr_model.predict(X_test) / 10


    # Calculate fold RMSE using the current sklearn-compatible method
    fold_rmse = np.sqrt(
        mean_squared_error(
            y_val,
            oof_xgb[valid_idx]
        )
    )

    # Print the fold RMSE
    print(
        "XGBoost fold RMSE:",
        round(fold_rmse, 4)
    )


# Print completion message
print("\n10-fold base-model training completed.")

========== Fold 1/10 ==========

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

XGBoost fold RMSE: 0.6238

========== Fold 2/10 ==========

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

XGBoost fold RMSE: 0.6332

========== Fold 3/10 ==========

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

XGBoost fold RMSE: 0.769

========== Fold 4/10 ==========

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

XGBoost fold RMSE: 0.6464

========== Fold 5/10 ==========

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

XGBoost fold RMSE: 0.7137

========== Fold 6/10 ==========

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

XGBoost fold RMSE: 0.7561

========== Fold 7/10 ==========
XGBoost fold RMSE: 0.7214

========== Fold 8/10 ==========

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

XGBoost fold RMSE: 0.676

========== Fold 9/10 ==========

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

XGBoost fold RMSE: 0.7622

========== Fold 10/10 ==========

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

XGBoost fold RMSE: 0.7018

10-fold base-model training completed.

In [55]:
# Define a helper function to calculate RMSE and Pearson correlation
def evaluate_model(name, y_true, predictions):

    # Calculate RMSE using the sklearn-compatible formula
    rmse = np.sqrt(
        mean_squared_error(
            y_true,
            predictions
        )
    )

    # Calculate Pearson correlation
    pearson = pearsonr(
        y_true,
        predictions
    )[0]

    # Print the model name
    print(f"{name}")

    # Print RMSE
    print(f"  RMSE: {rmse:.4f}")

    # Print Pearson correlation
    print(f"  Pearson: {pearson:.4f}")

    # Return both metrics
    return rmse, pearson


# Evaluate XGBoost OOF predictions
xgb_score = evaluate_model(
    "XGBoost",
    y,
    oof_xgb
)

# Evaluate LightGBM OOF predictions
lgb_score = evaluate_model(
    "LightGBM",
    y,
    oof_lgb
)

# Evaluate CatBoost OOF predictions
cat_score = evaluate_model(
    "CatBoost",
    y,
    oof_cat
)

# Evaluate Random Forest OOF predictions
rf_score = evaluate_model(
    "Random Forest",
    y,
    oof_rf
)

# Evaluate Ridge OOF predictions
ridge_score = evaluate_model(
    "Ridge",
    y,
    oof_ridge
)

# Evaluate SVR OOF predictions
svr_score = evaluate_model(
    "SVR",
    y,
    oof_svr
)

XGBoost
  RMSE: 0.7022
  Pearson: 0.8260
LightGBM
  RMSE: 0.7093
  Pearson: 0.8210
CatBoost
  RMSE: 0.7166
  Pearson: 0.8258
Random Forest
  RMSE: 0.7436
  Pearson: 0.8052
Ridge
  RMSE: 0.7549
  Pearson: 0.7984
SVR
  RMSE: 0.7741
  Pearson: 0.7807

In [56]:
# Combine all out-of-fold base-model predictions into one matrix
meta_train = np.column_stack([
    oof_xgb,
    oof_lgb,
    oof_cat,
    oof_rf,
    oof_ridge,
    oof_svr
])

# Combine all test predictions into one matrix
meta_test = np.column_stack([
    test_xgb,
    test_lgb,
    test_cat,
    test_rf,
    test_ridge,
    test_svr
])

# Print the meta-feature shapes
print("Meta train shape:", meta_train.shape)
print("Meta test shape:", meta_test.shape)


# Create the Ridge meta-model
meta_model = Ridge(
    alpha=1.0
)

# Train the meta-model using ONLY out-of-fold predictions
meta_model.fit(
    meta_train,
    y
)

# Generate final OOF predictions from the stacking model
stacked_oof = meta_model.predict(
    meta_train
)

# Calculate stacking RMSE
stacked_rmse = np.sqrt(
    mean_squared_error(
        y,
        stacked_oof
    )
)

# Calculate stacking Pearson correlation
stacked_pearson = pearsonr(
    y,
    stacked_oof
)[0]

# Print stacking performance
print("\n===== STACKING RESULTS =====")
print(
    "Stacking RMSE:",
    round(stacked_rmse, 4)
)
print(
    "Stacking Pearson:",
    round(stacked_pearson, 4)
)


# Display the learned meta-model weights
print("\nMeta-model coefficients:")

# Define model names
model_names = [
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "Random Forest",
    "Ridge",
    "SVR"
]

# Print each model's learned coefficient
for name, coefficient in zip(
    model_names,
    meta_model.coef_
):
    print(
        f"{name}: {coefficient:.4f}"
    )

Meta train shape: (769, 6)
Meta test shape: (216, 6)

===== STACKING RESULTS =====
Stacking RMSE: 0.6685
Stacking Pearson: 0.8417

Meta-model coefficients:
XGBoost: 0.1666
LightGBM: 0.0638
CatBoost: 0.1679
Random Forest: 0.2728
Ridge: 0.2052
SVR: 0.2631

In [57]:
# Create the final XGBoost model using all training data
final_xgb = XGBRegressor(
    n_estimators=1000,
    learning_rate=0.025,
    max_depth=5,
    min_child_weight=5,
    subsample=0.85,
    colsample_bytree=0.85,
    reg_alpha=0.1,
    reg_lambda=2.0,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

# Train XGBoost on all training samples
final_xgb.fit(
    X_train,
    y
)

# Generate predictions on the complete training set
train_pred_xgb = final_xgb.predict(X_train)

# Generate predictions on the test set
final_test_xgb = final_xgb.predict(X_test)


# Create the final LightGBM model
final_lgb = LGBMRegressor(
    n_estimators=1000,
    learning_rate=0.025,
    max_depth=6,
    num_leaves=31,
    subsample=0.85,
    colsample_bytree=0.85,
    reg_alpha=0.1,
    reg_lambda=2.0,
    random_state=42,
    verbosity=-1,
    n_jobs=-1
)

# Train LightGBM on all training data
final_lgb.fit(
    X_train,
    y
)

# Generate training predictions
train_pred_lgb = final_lgb.predict(X_train)

# Generate test predictions
final_test_lgb = final_lgb.predict(X_test)


# Create the final CatBoost model
final_cat = CatBoostRegressor(
    iterations=1000,
    depth=6,
    learning_rate=0.03,
    loss_function="RMSE",
    verbose=False,
    random_seed=42
)

# Train CatBoost on all training data
final_cat.fit(
    X_train,
    y
)

# Generate training predictions
train_pred_cat = final_cat.predict(X_train)

# Generate test predictions
final_test_cat = final_cat.predict(X_test)


# Create the final Random Forest model
final_rf = RandomForestRegressor(
    n_estimators=500,
    max_features=0.75,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

# Train Random Forest on all training data
final_rf.fit(
    X_train,
    y
)

# Generate training predictions
train_pred_rf = final_rf.predict(X_train)

# Generate test predictions
final_test_rf = final_rf.predict(X_test)


# Create the final Ridge model
final_ridge = Ridge(
    alpha=10.0
)

# Train Ridge on all training data
final_ridge.fit(
    X_train,
    y
)

# Generate training predictions
train_pred_ridge = final_ridge.predict(X_train)

# Generate test predictions
final_test_ridge = final_ridge.predict(X_test)


# Create the final SVR model
final_svr = SVR(
    C=10.0,
    epsilon=0.05,
    gamma="scale"
)

# Train SVR on all training data
final_svr.fit(
    X_train,
    y
)

# Generate training predictions
train_pred_svr = final_svr.predict(X_train)

# Generate test predictions
final_test_svr = final_svr.predict(X_test)


# Combine all full-training predictions
meta_train_full = np.column_stack([
    train_pred_xgb,
    train_pred_lgb,
    train_pred_cat,
    train_pred_rf,
    train_pred_ridge,
    train_pred_svr
])


# Combine all final test predictions
meta_test_final = np.column_stack([
    final_test_xgb,
    final_test_lgb,
    final_test_cat,
    final_test_rf,
    final_test_ridge,
    final_test_svr
])


# Use the previously trained OOF meta-model
final_train_predictions = meta_model.predict(
    meta_train_full
)

# Generate final test predictions
final_test_predictions = meta_model.predict(
    meta_test_final
)


# Calculate mandatory training RMSE
training_rmse = np.sqrt(
    mean_squared_error(
        y,
        final_train_predictions
    )
)

# Calculate training Pearson correlation
training_pearson = pearsonr(
    y,
    final_train_predictions
)[0]


# Print training metrics
print("===== FINAL TRAINING METRICS =====")

print(
    "Training RMSE:",
    round(training_rmse, 4)
)

print(
    "Training Pearson:",
    round(training_pearson, 4)
)


# Print test prediction statistics
print("\n===== TEST PREDICTIONS =====")

print(
    "Minimum:",
    round(final_test_predictions.min(), 4)
)

print(
    "Maximum:",
    round(final_test_predictions.max(), 4)
)

print(
    "Mean:",
    round(final_test_predictions.mean(), 4)
)

print(
    "Number of predictions:",
    len(final_test_predictions)
)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

===== FINAL TRAINING METRICS =====
Training RMSE: 0.195
Training Pearson: 0.9888

===== TEST PREDICTIONS =====
Minimum: 1.8075
Maximum: 4.9914
Mean: 3.3175
Number of predictions: 216

In [61]:
# Create the submission dataframe
submission_v3 = pd.DataFrame({
    "filename": test_df["filename"],
    "label": final_test_predictions
})

# Make sure predictions stay within the valid 0-5 scoring range
submission_v3["label"] = submission_v3["label"].clip(
    0,
    5
)

# Define the output file path
SUBMISSION_V3_PATH = "/kaggle/working/submission_v3.csv"

# Save the submission file
submission_v3.to_csv(
    SUBMISSION_V3_PATH,
    index=False
)

# Print the saved file location
print("Saved:", SUBMISSION_V3_PATH)

# Print the submission shape
print("Submission shape:", submission_v3.shape)

# Display the first five predictions
display(submission_v3.head())

Saved: /kaggle/working/submission_v3.csv
Submission shape: (216, 2)

        filename     label
0  audio_128.wav  3.492098
1  audio_156.wav  3.844662
2   audio_19.wav  3.740711
3  audio_108.wav  1.977067
4  audio_206.wav  2.652639

In [62]:
# Reload the saved submission file
check_submission = pd.read_csv(
    SUBMISSION_V3_PATH
)

# Check the number of rows
print(
    "Rows:",
    len(check_submission)
)

# Check the column names
print(
    "Columns:",
    check_submission.columns.tolist()
)

# Check for missing values
print(
    "Missing values:",
    check_submission.isna().sum().sum()
)

# Check that filenames match the original test order
print(
    "Filename order correct:",
    check_submission["filename"].equals(
        test_df["filename"]
    )
)

# Check prediction range
print(
    "Minimum label:",
    check_submission["label"].min()
)

print(
    "Maximum label:",
    check_submission["label"].max()
)

# Display final validation message
if (
    len(check_submission) == 216
    and check_submission.columns.tolist() == ["filename", "label"]
    and check_submission.isna().sum().sum() == 0
    and check_submission["filename"].equals(test_df["filename"])
):
    print("\n✅ submission_v3.csv is valid.")
else:
    print("\n❌ Submission validation failed.")

Rows: 216
Columns: ['filename', 'label']
Missing values: 0
Filename order correct: True
Minimum label: 1.8075166669194616
Maximum label: 4.991354849327888

✅ submission_v3.csv is valid.

In [4]:
# Install packages needed for Whisper ASR and linguistic feature extraction
!pip install -q transformers accelerate sentencepiece

In [5]:
import os
import re
import gc
import json
import numpy as np
import pandas as pd

# PyTorch for GPU inference
import torch

# Whisper pipeline
from transformers import pipeline

# Progress bar
from tqdm.auto import tqdm

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch version: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4

In [6]:
# Select Whisper model
WHISPER_MODEL = "openai/whisper-large-v3-turbo"

# Use GPU 0
DEVICE = 0 if torch.cuda.is_available() else -1

# Load Whisper ASR pipeline
whisper_pipe = pipeline(
    "automatic-speech-recognition",
    model=WHISPER_MODEL,
    device=DEVICE,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

print("Whisper loaded successfully.")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.26k [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.62GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/587 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/3.77k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/283k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.71M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/494k [00:00<?, ?B/s]

normalizer.json:   0%|          | 0.00/52.7k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.19k [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/340 [00:00<?, ?B/s]

Whisper loaded successfully.

In [10]:
import os
import pandas as pd

# Dataset paths
DATA_DIR = "/kaggle/input/competitions/shl-hiring-assessment-2026/Dataset_Final"

TRAIN_DIR = os.path.join(DATA_DIR, "train")
TEST_DIR = os.path.join(DATA_DIR, "test")

TRAIN_CSV = os.path.join(DATA_DIR, "train.csv")
TEST_CSV = os.path.join(DATA_DIR, "test.csv")

# Load metadata
train_df = pd.read_csv(TRAIN_CSV)
test_df = pd.read_csv(TEST_CSV)

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)
print("Train columns:", train_df.columns.tolist())
print("TRAIN_DIR:", TRAIN_DIR)

Train shape: (769, 2)
Test shape: (216, 2)
Train columns: ['filename', 'label']
TRAIN_DIR: /kaggle/input/competitions/shl-hiring-assessment-2026/Dataset_Final/train

In [11]:
sample_file = os.path.join(
    TRAIN_DIR,
    train_df.iloc[0]["filename"]
)

print("Sample file:", sample_file)
print("File exists:", os.path.exists(sample_file))

Sample file: /kaggle/input/competitions/shl-hiring-assessment-2026/Dataset_Final/train/audio_192.wav
File exists: True

In [12]:
from transformers import pipeline
import torch

WHISPER_MODEL = "openai/whisper-large-v3-turbo"

whisper_pipe = pipeline(
    "automatic-speech-recognition",
    model=WHISPER_MODEL,
    device=0 if torch.cuda.is_available() else -1,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

print("Whisper loaded.")

Loading weights:   0%|          | 0/587 [00:00<?, ?it/s]

Whisper loaded.

In [13]:
result = whisper_pipe(
    sample_file,
    return_timestamps=True
)

print(result["text"])

[transformers] Using custom `forced_decoder_ids` from the (generation) config. This is deprecated in favor of the `task` and `language` flags/config options.
[transformers] Transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English. This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`. See https://github.com/huggingface/transformers/pull/28687 for more details.
[transformers] Passing `generation_config` together with generation-related arguments=({'suppress_tokens', 'begin_suppress_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer WhisperTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

 Well, the playground is very, very beautiful and fun, there are, there are playtons like the merry-go-round, the swing, the students usually enjoy the swing, it has to be like, It's more like a game of care, because one sits on it and the other takes on it and we'll have to push, then the merry-go-round, they just climb on it. And most of them play football in some parks, while others just swing. Some of the kids like to build sand castles. and most times you hear the sound of screaming children laughing tears.

In [14]:
# Transcribe all 769 training audio files

from tqdm.auto import tqdm

train_transcripts = []

for filename in tqdm(
    train_df["filename"],
    desc="Transcribing training audio"
):
    
    audio_path = os.path.join(
        TRAIN_DIR,
        filename
    )
    
    try:
        result = whisper_pipe(
            audio_path,
            return_timestamps=True
        )
        
        text = result.get("text", "")
        text = re.sub(r"\s+", " ", text).strip()
        
    except Exception as e:
        print(f"\nError: {filename} -> {e}")
        text = ""
    
    train_transcripts.append(text)

print("\nTraining transcription completed.")
print("Number of transcripts:", len(train_transcripts))

Transcribing training audio:   0%|          | 0/769 [00:00<?, ?it/s]

[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

Training transcription completed.
Number of transcripts: 769

In [15]:
# Save all 769 Whisper transcripts safely

train_transcripts_df = pd.DataFrame({
    "filename": train_df["filename"],
    "transcript": train_transcripts
})

train_transcripts_df.to_csv(
    "/kaggle/working/train_transcripts.csv",
    index=False
)

print("Saved successfully!")
print("Shape:", train_transcripts_df.shape)
print("File:", "/kaggle/working/train_transcripts.csv")

Saved successfully!
Shape: (769, 2)
File: /kaggle/working/train_transcripts.csv

In [20]:
# Check transcript quality

empty_count = (
    train_transcripts_df["transcript"]
    .fillna("")
    .str.strip()
    .eq("")
    .sum()
)

print("Total transcripts:", len(train_transcripts_df))
print("Empty transcripts:", empty_count)
print(
    "Successful transcripts:",
    len(train_transcripts_df) - empty_count
)

Total transcripts: 769
Empty transcripts: 0
Successful transcripts: 769

In [21]:
# ============================================================
# V4 — Linguistic / Grammar Feature Extraction
# ============================================================

import re
import numpy as np
import pandas as pd

# Common English filler words
FILLER_WORDS = {
    "um", "uh", "erm", "hmm", "ah",
    "like", "actually", "basically", "literally"
}


def extract_linguistic_features(text, duration):
    """
    Extract linguistic, fluency and vocabulary features
    from a Whisper transcript.
    """

    # Make sure text is a valid string
    text = str(text).lower().strip()

    # Extract alphabetic words
    words = re.findall(
        r"\b[a-zA-Z']+\b",
        text
    )

    word_count = len(words)

    # Unique vocabulary
    unique_words = len(set(words))

    # Type-token ratio
    type_token_ratio = (
        unique_words / word_count
        if word_count > 0 else 0
    )

    # Split into sentences
    sentences = re.split(
        r"[.!?]+",
        text
    )

    sentences = [
        s.strip()
        for s in sentences
        if s.strip()
    ]

    sentence_count = len(sentences)

    # Sentence lengths
    sentence_lengths = []

    for sentence in sentences:

        sentence_words = re.findall(
            r"\b[a-zA-Z']+\b",
            sentence
        )

        sentence_lengths.append(
            len(sentence_words)
        )

    if sentence_lengths:

        avg_sentence_length = np.mean(
            sentence_lengths
        )

        max_sentence_length = np.max(
            sentence_lengths
        )

        sentence_length_std = np.std(
            sentence_lengths
        )

    else:

        avg_sentence_length = 0
        max_sentence_length = 0
        sentence_length_std = 0

    # Protect against zero duration
    duration = max(float(duration), 1.0)

    # Speaking rate
    words_per_second = (
        word_count / duration
    )

    words_per_minute = (
        words_per_second * 60
    )

    # --------------------------------------------------------
    # Filler words
    # --------------------------------------------------------

    filler_count = 0

    for filler in FILLER_WORDS:

        filler_count += len(
            re.findall(
                r"\b" + re.escape(filler) + r"\b",
                text
            )
        )

    filler_ratio = (
        filler_count / word_count
        if word_count > 0 else 0
    )

    # --------------------------------------------------------
    # Repeated consecutive words
    # --------------------------------------------------------

    repeated_words = 0

    for i in range(1, len(words)):

        if words[i] == words[i - 1]:

            repeated_words += 1

    repeated_word_ratio = (
        repeated_words / word_count
        if word_count > 0 else 0
    )

    # --------------------------------------------------------
    # Word characteristics
    # --------------------------------------------------------

    if word_count > 0:

        avg_word_length = np.mean([
            len(word)
            for word in words
        ])

        word_length_std = np.std([
            len(word)
            for word in words
        ])

    else:

        avg_word_length = 0
        word_length_std = 0

    # Long vocabulary
    long_words = sum(
        len(word) >= 7
        for word in words
    )

    long_word_ratio = (
        long_words / word_count
        if word_count > 0 else 0
    )

    # --------------------------------------------------------
    # Punctuation / structure
    # --------------------------------------------------------

    comma_count = text.count(",")

    question_count = text.count("?")

    exclamation_count = text.count("!")

    # Character count
    character_count = len(text)

    # Average characters per word
    avg_chars_per_word = (
        character_count / word_count
        if word_count > 0 else 0
    )

    # --------------------------------------------------------
    # Return feature dictionary
    # --------------------------------------------------------

    return {

        "word_count":
            word_count,

        "unique_word_count":
            unique_words,

        "type_token_ratio":
            type_token_ratio,

        "sentence_count":
            sentence_count,

        "avg_sentence_length":
            avg_sentence_length,

        "max_sentence_length":
            max_sentence_length,

        "sentence_length_std":
            sentence_length_std,

        "words_per_second":
            words_per_second,

        "words_per_minute":
            words_per_minute,

        "filler_count":
            filler_count,

        "filler_ratio":
            filler_ratio,

        "repeated_words":
            repeated_words,

        "repeated_word_ratio":
            repeated_word_ratio,

        "avg_word_length":
            avg_word_length,

        "word_length_std":
            word_length_std,

        "long_word_ratio":
            long_word_ratio,

        "comma_count":
            comma_count,

        "question_count":
            question_count,

        "exclamation_count":
            exclamation_count,

        "character_count":
            character_count,

        "avg_chars_per_word":
            avg_chars_per_word
    }

In [23]:
# ============================================================
# Recreate audio durations for the 769 training files
# ============================================================

import librosa
from tqdm.auto import tqdm

train_durations = []

for filename in tqdm(
    train_df["filename"],
    desc="Reading training audio durations"
):
    
    audio_path = os.path.join(
        TRAIN_DIR,
        filename
    )
    
    # Get duration without loading the complete audio
    duration = librosa.get_duration(
        path=audio_path
    )
    
    train_durations.append(duration)

print("\nDuration extraction completed.")
print("Number of durations:", len(train_durations))
print("First 5 durations:", train_durations[:5])

Reading training audio durations:   0%|          | 0/769 [00:00<?, ?it/s]

Duration extraction completed.
Number of durations: 769
First 5 durations: [60.508375, 60.0746875, 60.0746875, 45.06, 45.3]

In [24]:
# ============================================================
# Extract linguistic features
# ============================================================

linguistic_features = []

for i, text in enumerate(
    tqdm(
        train_transcripts,
        desc="Extracting linguistic features"
    )
):
    
    # Use recreated duration
    duration = train_durations[i]
    
    # Extract linguistic features
    features = extract_linguistic_features(
        text,
        duration
    )
    
    linguistic_features.append(features)


# Convert to DataFrame
ling_train = pd.DataFrame(
    linguistic_features
)

print("\nLinguistic feature shape:", ling_train.shape)

display(ling_train.head())

Extracting linguistic features:   0%|          | 0/769 [00:00<?, ?it/s]

Linguistic feature shape: (769, 21)

,word_count,unique_word_count,type_token_ratio,sentence_count,avg_sentence_length,max_sentence_length,sentence_length_std,words_per_second,words_per_minute,filler_count,...,repeated_words,repeated_word_ratio,avg_word_length,word_length_std,long_word_ratio,comma_count,question_count,exclamation_count,character_count,avg_chars_per_word
0,99,63,0.636364,4,24.750000,65,23.284920,1.636137,98.168229,4,...,1,0.010101,4.060606,1.802457,0.111111,12,0,0,516,5.212121
1,111,52,0.468468,4,27.750000,63,20.801142,1.847700,110.862000,5,...,1,0.009009,4.351351,2.362045,0.144144,2,0,0,598,5.387387
2,151,78,0.516556,6,25.166667,87,27.781389,2.513538,150.812270,1,...,0,0.000000,3.874172,1.943931,0.112583,3,0,0,744,4.927152
3,98,41,0.418367,1,98.000000,98,0.000000,2.174878,130.492676,0,...,2,0.020408,3.632653,1.618690,0.030612,0,0,0,455,4.642857
4,77,45,0.584416,1,77.000000,77,0.000000,1.699779,101.986755,0,...,3,0.038961,3.883117,1.967093,0.090909,0,0,0,375,4.870130

In [25]:
# Check data quality

print(
    "Missing values:",
    ling_train.isna().sum().sum()
)

print(
    "Infinite values:",
    np.isinf(ling_train.select_dtypes(
        include=np.number
    )).sum().sum()
)

Missing values: 0
Infinite values: 0

In [26]:
# Save linguistic features so we don't lose them

ling_train.to_csv(
    "/kaggle/working/train_linguistic_features.csv",
    index=False
)

print("Saved successfully.")
print("Shape:", ling_train.shape)

Saved successfully.
Shape: (769, 21)

In [27]:
# ============================================================
# Transcribe all 216 test audio files
# ============================================================

test_transcripts = []

for filename in tqdm(
    test_df["filename"],
    desc="Transcribing test audio"
):
    
    audio_path = os.path.join(
        TEST_DIR,
        filename
    )
    
    try:
        result = whisper_pipe(
            audio_path,
            return_timestamps=True
        )
        
        text = result.get("text", "")
        text = re.sub(r"\s+", " ", text).strip()
        
    except Exception as e:
        print(f"\nError: {filename} -> {e}")
        text = ""
    
    test_transcripts.append(text)

print("\nTest transcription completed.")
print("Number of transcripts:", len(test_transcripts))

Transcribing test audio:   0%|          | 0/216 [00:00<?, ?it/s]

[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
[transformers] Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.

Test transcription completed.
Number of transcripts: 216

In [28]:
test_transcripts_df = pd.DataFrame({
    "filename": test_df["filename"],
    "transcript": test_transcripts
})

test_transcripts_df.to_csv(
    "/kaggle/working/test_transcripts.csv",
    index=False
)

print("Test transcripts saved.")
print("Shape:", test_transcripts_df.shape)

print(
    "Empty transcripts:",
    test_transcripts_df["transcript"]
    .fillna("")
    .str.strip()
    .eq("")
    .sum()
)

Test transcripts saved.
Shape: (216, 2)
Empty transcripts: 0

In [29]:
# ============================================================
# Extract linguistic features for TEST data
# ============================================================

linguistic_test_features = []

for i, text in enumerate(
    tqdm(
        test_transcripts,
        desc="Extracting test linguistic features"
    )
):
    
    # Use the duration we need for this test file
    audio_path = os.path.join(
        TEST_DIR,
        test_df.iloc[i]["filename"]
    )
    
    duration = librosa.get_duration(
        path=audio_path
    )
    
    # Extract linguistic features
    features = extract_linguistic_features(
        text,
        duration
    )
    
    linguistic_test_features.append(features)


# Convert to DataFrame
ling_test = pd.DataFrame(
    linguistic_test_features
)

print("\nTest linguistic feature shape:", ling_test.shape)

display(ling_test.head())

Extracting test linguistic features:   0%|          | 0/216 [00:00<?, ?it/s]

Test linguistic feature shape: (216, 21)

,word_count,unique_word_count,type_token_ratio,sentence_count,avg_sentence_length,max_sentence_length,sentence_length_std,words_per_second,words_per_minute,filler_count,...,repeated_words,repeated_word_ratio,avg_word_length,word_length_std,long_word_ratio,comma_count,question_count,exclamation_count,character_count,avg_chars_per_word
0,89,47,0.528090,5,17.800000,24,6.209670,1.975144,118.508655,0,...,0,0.000000,3.853933,2.008692,0.146067,1,0,0,447,5.022472
1,67,55,0.820896,4,16.750000,22,4.322904,1.489905,89.394295,0,...,0,0.000000,5.701493,2.927048,0.388060,1,0,0,453,6.761194
2,104,68,0.653846,7,14.857143,25,6.311635,2.310495,138.629699,1,...,0,0.000000,4.509615,2.409896,0.182692,12,0,0,591,5.682692
3,65,44,0.676923,1,65.000000,65,0.000000,1.102068,66.124110,0,...,4,0.061538,4.461538,2.170267,0.200000,0,0,0,359,5.523077
4,93,54,0.580645,1,93.000000,93,0.000000,2.064831,123.889876,0,...,2,0.021505,3.698925,2.041426,0.107527,0,0,0,436,4.688172

In [78]:
# Check test linguistic features

print(
    "Missing values:",
    ling_test.isna().sum().sum()
)

print(
    "Infinite values:",
    np.isinf(
        ling_test.select_dtypes(
            include=np.number
        )
    ).sum().sum()
)

Missing values: 0
Infinite values: 0

In [79]:
# Check which important V3 variables are currently available

variables_to_check = [
    "train_wav2vec",
    "test_wav2vec",
    "X_train_final",
    "X_test_final",
    "acoustic_train",
    "acoustic_test",
    "ling_train",
    "ling_test"
]

for var in variables_to_check:
    print(
        f"{var}:",
        "AVAILABLE" if var in globals() else "NOT AVAILABLE"
    )

train_wav2vec: NOT AVAILABLE
test_wav2vec: NOT AVAILABLE
X_train_final: NOT AVAILABLE
X_test_final: NOT AVAILABLE
acoustic_train: AVAILABLE
acoustic_test: AVAILABLE
ling_train: AVAILABLE
ling_test: AVAILABLE

In [64]:
# Save test linguistic features
ling_test.to_csv(
    "/kaggle/working/test_linguistic_features.csv",
    index=False
)

print("Saved:", ling_test.shape)

Saved: (216, 21)

In [82]:
# ============================================================
# V4 — Reliable Acoustic Feature Extraction
# ============================================================

import os
import numpy as np
import pandas as pd
import librosa
from tqdm.auto import tqdm


def extract_acoustic_features_v4(audio_path):
    """
    Extract 25 acoustic/prosodic features from one WAV file.
    """

    # Load audio at 16 kHz
    y, sr = librosa.load(
        audio_path,
        sr=16000,
        mono=True
    )

    # Handle empty audio
    if len(y) == 0:
        return np.zeros(25, dtype=np.float32)

    # Duration
    duration = len(y) / sr

    # RMS energy
    rms = librosa.feature.rms(y=y)[0]

    # Zero crossing rate
    zcr = librosa.feature.zero_crossing_rate(y)[0]

    # Spectral centroid
    centroid = librosa.feature.spectral_centroid(
        y=y,
        sr=sr
    )[0]

    # Spectral bandwidth
    bandwidth = librosa.feature.spectral_bandwidth(
        y=y,
        sr=sr
    )[0]

    # Spectral rolloff
    rolloff = librosa.feature.spectral_rolloff(
        y=y,
        sr=sr
    )[0]

    # Pitch
    f0 = librosa.yin(
        y,
        fmin=70,
        fmax=400,
        sr=sr
    )

    # Valid pitch values
    valid_f0 = f0[np.isfinite(f0)]

    # Onset strength
    onset = librosa.onset.onset_strength(
        y=y,
        sr=sr
    )

    # Energy change
    energy_change = np.diff(rms)

    # Silence ratio
    silence_ratio = np.mean(
        rms < (np.max(rms) * 0.05)
    )

    # Speech ratio
    speech_ratio = 1.0 - silence_ratio

    # Onset rate
    onset_count = len(
        librosa.onset.onset_detect(
            y=y,
            sr=sr
        )
    )

    onset_rate = (
        onset_count / max(duration, 1e-6)
    )

    # Pitch statistics
    if len(valid_f0) > 0:

        pitch_mean = np.mean(valid_f0)
        pitch_std = np.std(valid_f0)
        pitch_min = np.min(valid_f0)
        pitch_max = np.max(valid_f0)

    else:

        pitch_mean = 0.0
        pitch_std = 0.0
        pitch_min = 0.0
        pitch_max = 0.0

    # Exactly 25 features
    features = [

        duration,

        np.mean(rms),
        np.std(rms),
        np.min(rms),
        np.max(rms),

        np.mean(zcr),
        np.std(zcr),

        np.mean(centroid),
        np.std(centroid),

        np.mean(bandwidth),
        np.std(bandwidth),

        np.mean(rolloff),
        np.std(rolloff),

        pitch_mean,
        pitch_std,
        pitch_min,
        pitch_max,

        np.mean(onset),
        np.std(onset),

        np.mean(energy_change)
            if len(energy_change) else 0.0,

        np.std(energy_change)
            if len(energy_change) else 0.0,

        silence_ratio,
        speech_ratio,

        onset_rate,

        len(valid_f0)
    ]

    return np.asarray(
        features,
        dtype=np.float32
    )


# ------------------------------------------------------------
# TRAIN ACOUSTIC FEATURES
# ------------------------------------------------------------

train_acoustic = []

for filename in tqdm(
    train_df["filename"].tolist(),
    desc="Train acoustic features"
):

    audio_path = os.path.join(
        TRAIN_DIR,
        filename
    )

    train_acoustic.append(
        extract_acoustic_features_v4(
            audio_path
        )
    )


# Convert list of vectors → 2D matrix
train_acoustic = np.vstack(
    train_acoustic
)


# ------------------------------------------------------------
# TEST ACOUSTIC FEATURES
# ------------------------------------------------------------

test_acoustic = []

for filename in tqdm(
    test_df["filename"].tolist(),
    desc="Test acoustic features"
):

    audio_path = os.path.join(
        TEST_DIR,
        filename
    )

    test_acoustic.append(
        extract_acoustic_features_v4(
            audio_path
        )
    )


# Convert list of vectors → 2D matrix
test_acoustic = np.vstack(
    test_acoustic
)


# ------------------------------------------------------------
# CHECK
# ------------------------------------------------------------

print(
    "Train acoustic shape:",
    train_acoustic.shape
)

print(
    "Test acoustic shape:",
    test_acoustic.shape
)

print(
    "Train NaNs:",
    np.isnan(train_acoustic).sum()
)

print(
    "Test NaNs:",
    np.isnan(test_acoustic).sum()
)

Train acoustic features:   0%|          | 0/769 [00:00<?, ?it/s]

Test acoustic features:   0%|          | 0/216 [00:00<?, ?it/s]

Train acoustic shape: (769, 25)
Test acoustic shape: (216, 25)
Train NaNs: 0
Test NaNs: 0

In [83]:
# Save acoustic features
np.save(
    "/kaggle/working/train_acoustic_v4.npy",
    train_acoustic
)

np.save(
    "/kaggle/working/test_acoustic_v4.npy",
    test_acoustic
)

print("Acoustic V4 features saved.")

Acoustic V4 features saved.

In [86]:
# ============================================================
# V4 — Load and combine all feature groups
# ============================================================

import numpy as np
import pandas as pd

# ------------------------------------------------------------
# 1. Load Wav2Vec2 embeddings
# ------------------------------------------------------------

train_embeddings = np.load(
    "/kaggle/working/train_wav2vec.npy"
)

test_embeddings = np.load(
    "/kaggle/working/test_wav2vec.npy"
)

print("Wav2Vec2 train:", train_embeddings.shape)
print("Wav2Vec2 test :", test_embeddings.shape)


# ------------------------------------------------------------
# 2. Load acoustic features
# ------------------------------------------------------------

train_acoustic = np.load(
    "/kaggle/working/train_acoustic_v4.npy"
)

test_acoustic = np.load(
    "/kaggle/working/test_acoustic_v4.npy"
)

print("Acoustic train:", train_acoustic.shape)
print("Acoustic test :", test_acoustic.shape)


# ------------------------------------------------------------
# 3. Load linguistic features
# ------------------------------------------------------------

ling_train = pd.read_csv(
    "/kaggle/working/train_linguistic_features.csv"
)

ling_test = pd.read_csv(
    "/kaggle/working/test_linguistic_features.csv"
)

ling_train_array = ling_train.to_numpy(
    dtype=np.float32
)

ling_test_array = ling_test.to_numpy(
    dtype=np.float32
)

print("Linguistic train:", ling_train_array.shape)
print("Linguistic test :", ling_test_array.shape)


# ------------------------------------------------------------
# 4. Combine Wav2Vec2 + acoustic + linguistic
# ------------------------------------------------------------

X_train_v4_raw = np.hstack([
    train_embeddings,
    train_acoustic,
    ling_train_array
])

X_test_v4_raw = np.hstack([
    test_embeddings,
    test_acoustic,
    ling_test_array
])


# ------------------------------------------------------------
# 5. Final shape check
# ------------------------------------------------------------

print("\n========================================")
print("V4 FEATURE MATRIX")
print("========================================")

print(
    "Train:",
    X_train_v4_raw.shape
)

print(
    "Test :",
    X_test_v4_raw.shape
)

print(
    "Train NaNs:",
    np.isnan(X_train_v4_raw).sum()
)

print(
    "Test NaNs:",
    np.isnan(X_test_v4_raw).sum()
)

Wav2Vec2 train: (769, 1024)
Wav2Vec2 test : (216, 1024)
Acoustic train: (769, 25)
Acoustic test : (216, 25)
Linguistic train: (769, 21)
Linguistic test : (216, 21)

========================================
V4 FEATURE MATRIX
========================================
Train: (769, 1070)
Test : (216, 1070)
Train NaNs: 0
Test NaNs: 0

In [87]:
# ============================================================
# V4 — PCA for Wav2Vec2 + scaling for acoustic/linguistic
# ============================================================

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# ------------------------------------------------------------
# Separate feature groups
# ------------------------------------------------------------

# Wav2Vec2 = first 1024 columns
wav_train = X_train_v4_raw[:, :1024]
wav_test = X_test_v4_raw[:, :1024]

# Acoustic = next 25 columns
acoustic_train_v4 = X_train_v4_raw[:, 1024:1049]
acoustic_test_v4 = X_test_v4_raw[:, 1024:1049]

# Linguistic = final 21 columns
ling_train_v4 = X_train_v4_raw[:, 1049:]
ling_test_v4 = X_test_v4_raw[:, 1049:]


print("Wav2Vec2:", wav_train.shape)
print("Acoustic:", acoustic_train_v4.shape)
print("Linguistic:", ling_train_v4.shape)


# ------------------------------------------------------------
# Scale Wav2Vec2
# ------------------------------------------------------------

wav_scaler = StandardScaler()

wav_train_scaled = wav_scaler.fit_transform(
    wav_train
)

wav_test_scaled = wav_scaler.transform(
    wav_test
)


# ------------------------------------------------------------
# PCA — retain 95% variance
# ------------------------------------------------------------

pca = PCA(
    n_components=0.95,
    random_state=42
)

wav_train_pca = pca.fit_transform(
    wav_train_scaled
)

wav_test_pca = pca.transform(
    wav_test_scaled
)


print("\nWav2Vec2 original dimensions:", 1024)
print(
    "PCA dimensions:",
    wav_train_pca.shape[1]
)

print(
    "Explained variance:",
    round(
        pca.explained_variance_ratio_.sum(),
        4
    )
)

Wav2Vec2: (769, 1024)
Acoustic: (769, 25)
Linguistic: (769, 21)

Wav2Vec2 original dimensions: 1024
PCA dimensions: 99
Explained variance: 0.9506

In [88]:
# ============================================================
# Scale acoustic + linguistic features
# ============================================================

# Combine acoustic and linguistic features
small_train = np.hstack([
    acoustic_train_v4,
    ling_train_v4
])

small_test = np.hstack([
    acoustic_test_v4,
    ling_test_v4
])

print(
    "Acoustic + linguistic train:",
    small_train.shape
)

print(
    "Acoustic + linguistic test:",
    small_test.shape
)


# Standardize
small_scaler = StandardScaler()

small_train_scaled = small_scaler.fit_transform(
    small_train
)

small_test_scaled = small_scaler.transform(
    small_test
)


print("Scaling completed.")

Acoustic + linguistic train: (769, 46)
Acoustic + linguistic test: (216, 46)
Scaling completed.

In [89]:
# ============================================================
# Final V4 feature matrix
# ============================================================

X_train_v4 = np.hstack([
    wav_train_pca,
    small_train_scaled
])

X_test_v4 = np.hstack([
    wav_test_pca,
    small_test_scaled
])


print(
    "Final V4 train shape:",
    X_train_v4.shape
)

print(
    "Final V4 test shape:",
    X_test_v4.shape
)

print(
    "NaNs train:",
    np.isnan(X_train_v4).sum()
)

print(
    "NaNs test:",
    np.isnan(X_test_v4).sum()
)

Final V4 train shape: (769, 145)
Final V4 test shape: (216, 145)
NaNs train: 0
NaNs test: 0

In [90]:
# ============================================================
# V4 — 10-Fold Ensemble + OOF Stacking
# ============================================================

import numpy as np
import pandas as pd

from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

from scipy.stats import pearsonr
from tqdm.auto import tqdm


# ------------------------------------------------------------
# Target
# ------------------------------------------------------------

y = train_df["label"].values.astype(np.float32)

print("Target shape:", y.shape)


# ------------------------------------------------------------
# 10-fold cross-validation
# ------------------------------------------------------------

kf = KFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)


# ------------------------------------------------------------
# Model factory
# ------------------------------------------------------------

def create_models():

    return {

        "XGB": XGBRegressor(
            n_estimators=1000,
            learning_rate=0.025,
            max_depth=5,
            min_child_weight=5,
            subsample=0.85,
            colsample_bytree=0.85,
            reg_alpha=0.1,
            reg_lambda=2,
            objective="reg:squarederror",
            random_state=42,
            n_jobs=-1
        ),

        "LGBM": LGBMRegressor(
            n_estimators=1000,
            learning_rate=0.025,
            max_depth=6,
            num_leaves=31,
            subsample=0.85,
            colsample_bytree=0.85,
            reg_alpha=0.1,
            reg_lambda=2,
            random_state=42,
            verbosity=-1,
            n_jobs=-1
        ),

        "CAT": CatBoostRegressor(
            iterations=1000,
            depth=6,
            learning_rate=0.03,
            loss_function="RMSE",
            verbose=False,
            random_seed=42
        ),

        "RF": RandomForestRegressor(
            n_estimators=500,
            max_features=0.75,
            min_samples_leaf=2,
            random_state=42,
            n_jobs=-1
        ),

        "Ridge": Ridge(
            alpha=10.0
        ),

        "SVR": SVR(
            C=10,
            epsilon=0.05,
            gamma="scale"
        )
    }


# ------------------------------------------------------------
# Storage
# ------------------------------------------------------------

model_names = [
    "XGB",
    "LGBM",
    "CAT",
    "RF",
    "Ridge",
    "SVR"
]

oof_predictions = {
    name: np.zeros(len(y))
    for name in model_names
}

test_predictions = {
    name: np.zeros(len(X_test_v4))
    for name in model_names
}


# ------------------------------------------------------------
# Cross-validation
# ------------------------------------------------------------

for fold, (train_idx, valid_idx) in enumerate(
    kf.split(X_train_v4),
    start=1
):

    print(
        f"\n========== Fold {fold}/10 =========="
    )

    X_tr = X_train_v4[train_idx]
    X_val = X_train_v4[valid_idx]

    y_tr = y[train_idx]
    y_val = y[valid_idx]

    models = create_models()

    for name, model in models.items():

        print(
            f"Training {name}..."
        )

        # Train
        model.fit(
            X_tr,
            y_tr
        )

        # Validation prediction
        val_pred = model.predict(
            X_val
        )

        # Test prediction
        test_pred = model.predict(
            X_test_v4
        )

        # Store OOF prediction
        oof_predictions[name][valid_idx] = (
            val_pred
        )

        # Average test predictions across folds
        test_predictions[name] += (
            test_pred / 10
        )


print("\nAll folds completed.")

Target shape: (769,)

========== Fold 1/10 ==========
Training XGB...
Training LGBM...

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

Training CAT...
Training RF...
Training Ridge...
Training SVR...

========== Fold 2/10 ==========
Training XGB...
Training LGBM...

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

Training CAT...
Training RF...
Training Ridge...
Training SVR...

========== Fold 3/10 ==========
Training XGB...
Training LGBM...

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

Training CAT...
Training RF...
Training Ridge...
Training SVR...

========== Fold 4/10 ==========
Training XGB...
Training LGBM...

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

Training CAT...
Training RF...
Training Ridge...
Training SVR...

========== Fold 5/10 ==========
Training XGB...
Training LGBM...

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

Training CAT...
Training RF...
Training Ridge...
Training SVR...

========== Fold 6/10 ==========
Training XGB...
Training LGBM...

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

Training CAT...
Training RF...
Training Ridge...
Training SVR...

========== Fold 7/10 ==========
Training XGB...
Training LGBM...

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

Training CAT...
Training RF...
Training Ridge...
Training SVR...

========== Fold 8/10 ==========
Training XGB...
Training LGBM...

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

Training CAT...
Training RF...
Training Ridge...
Training SVR...

========== Fold 9/10 ==========
Training XGB...
Training LGBM...

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

Training CAT...
Training RF...
Training Ridge...
Training SVR...

========== Fold 10/10 ==========
Training XGB...
Training LGBM...

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

Training CAT...
Training RF...
Training Ridge...
Training SVR...

All folds completed.

In [91]:
# ============================================================
# Evaluate individual V4 models
# ============================================================

results = []

for name in model_names:

    rmse = np.sqrt(
        mean_squared_error(
            y,
            oof_predictions[name]
        )
    )

    pearson = pearsonr(
        y,
        oof_predictions[name]
    )[0]

    results.append({
        "Model": name,
        "RMSE": rmse,
        "Pearson": pearson
    })


results_df = pd.DataFrame(
    results
).sort_values(
    "RMSE"
)

display(results_df)

   Model      RMSE   Pearson
0    XGB  0.671268  0.841300
1   LGBM  0.674297  0.839207
2    CAT  0.681005  0.841868
3     RF  0.696706  0.829224
4  Ridge  0.748489  0.803893
5    SVR  0.770679  0.782762

In [92]:
# ============================================================
# V4 — Ridge Stacking
# ============================================================

# OOF predictions become meta features
meta_train = np.column_stack([
    oof_predictions[name]
    for name in model_names
])

# Test predictions become meta-test features
meta_test = np.column_stack([
    test_predictions[name]
    for name in model_names
])

print("Meta train:", meta_train.shape)
print("Meta test :", meta_test.shape)


# Meta learner
meta_model = Ridge(
    alpha=1.0
)

meta_model.fit(
    meta_train,
    y
)


# OOF stacked prediction
stacked_oof = meta_model.predict(
    meta_train
)


# Evaluate stack
stack_rmse = np.sqrt(
    mean_squared_error(
        y,
        stacked_oof
    )
)

stack_pearson = pearsonr(
    y,
    stacked_oof
)[0]


print("\n==============================")
print("V4 STACKING RESULTS")
print("==============================")

print(
    "OOF RMSE:",
    round(stack_rmse, 4)
)

print(
    "OOF Pearson:",
    round(stack_pearson, 4)
)

print(
    "\nV3 benchmark:"
)

print(
    "RMSE: 0.6685"
)

print(
    "Pearson: 0.8417"
)

Meta train: (769, 6)
Meta test : (216, 6)

==============================
V4 STACKING RESULTS
==============================
OOF RMSE: 0.6493
OOF Pearson: 0.8515

V3 benchmark:
RMSE: 0.6685
Pearson: 0.8417

In [93]:
# ============================================================
# V4 — Generate final test predictions
# ============================================================

# Meta-model prediction on test
v4_test_pred = meta_model.predict(
    meta_test
)

# Keep scores within the competition range
v4_test_pred = np.clip(
    v4_test_pred,
    0,
    5
)

print("Prediction count:", len(v4_test_pred))
print("Minimum:", v4_test_pred.min())
print("Maximum:", v4_test_pred.max())
print("Mean:", v4_test_pred.mean())

Prediction count: 216
Minimum: 1.8289431584705382
Maximum: 5.0
Mean: 3.321201210875349

In [95]:
# ============================================================
# V4 Submission
# ============================================================

submission_v4 = pd.DataFrame({
    "filename": test_df["filename"],
    "label": v4_test_pred
})

submission_v4.to_csv(
    "/kaggle/working/submission_v4.csv",
    index=False
)

print("Submission saved.")
print(submission_v4.head())
print("\nShape:", submission_v4.shape)

Submission saved.
        filename     label
0  audio_128.wav  3.300483
1  audio_156.wav  3.818739
2   audio_19.wav  4.189729
3  audio_108.wav  1.995750
4  audio_206.wav  2.607593

Shape: (216, 2)

In [96]:
# ============================================================
# Validate submission
# ============================================================

submission_check = pd.read_csv(
    "/kaggle/working/submission_v4.csv"
)

print("Rows:", len(submission_check))
print("Columns:", submission_check.columns.tolist())
print("Missing:", submission_check.isna().sum().sum())

print(
    "Filename order correct:",
    submission_check["filename"].equals(
        test_df["filename"]
    )
)

print(
    "Prediction range:",
    submission_check["label"].min(),
    "to",
    submission_check["label"].max()
)

Rows: 216
Columns: ['filename', 'label']
Missing: 0
Filename order correct: True
Prediction range: 1.8289431584705385 to 5.0

In [97]:
import os

files = os.listdir("/kaggle/working")

for f in files:
    if "submission" in f.lower():
        print(f)

submission_v3.csv
submission_v4.csv